# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vdms-demo/development/vdms_install

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vdms-demo/development/vdms_install/pmgd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vdms-demo/development/vdms_install/pmgd/CMakeFiles /home/vdms-demo/development/vdms_install/pmgd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vdms-demo/development/vdms_install/pmgd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dms

# Build rule for target.
dms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dms
.PHONY : dms

# fast build rule for target.
dms/fast:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/build
.PHONY : dms/fast

#=============================================================================
# Target rules for targets named vdms

# Build rule for target.
vdms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vdms
.PHONY : vdms

# fast build rule for target.
vdms/fast:
	$(MAKE) -f CMakeFiles/vdms.dir/build.make CMakeFiles/vdms.dir/build
.PHONY : vdms/fast

#=============================================================================
# Target rules for targets named vdms-utils

# Build rule for target.
vdms-utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vdms-utils
.PHONY : vdms-utils

# fast build rule for target.
vdms-utils/fast:
	$(MAKE) -f utils/CMakeFiles/vdms-utils.dir/build.make utils/CMakeFiles/vdms-utils.dir/build
.PHONY : vdms-utils/fast

#=============================================================================
# Target rules for targets named vdms_protobuf

# Build rule for target.
vdms_protobuf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vdms_protobuf
.PHONY : vdms_protobuf

# fast build rule for target.
vdms_protobuf/fast:
	$(MAKE) -f utils/src/protobuf/CMakeFiles/vdms_protobuf.dir/build.make utils/src/protobuf/CMakeFiles/vdms_protobuf.dir/build
.PHONY : vdms_protobuf/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f tests/CMakeFiles/unit_tests.dir/build.make tests/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named query_tests

# Build rule for target.
query_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 query_tests
.PHONY : query_tests

# fast build rule for target.
query_tests/fast:
	$(MAKE) -f tests/CMakeFiles/query_tests.dir/build.make tests/CMakeFiles/query_tests.dir/build
.PHONY : query_tests/fast

#=============================================================================
# Target rules for targets named vcl

# Build rule for target.
vcl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vcl
.PHONY : vcl

# fast build rule for target.
vcl/fast:
	$(MAKE) -f src/vcl/CMakeFiles/vcl.dir/build.make src/vcl/CMakeFiles/vcl.dir/build
.PHONY : vcl/fast

#=============================================================================
# Target rules for targets named vdms-client

# Build rule for target.
vdms-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vdms-client
.PHONY : vdms-client

# fast build rule for target.
vdms-client/fast:
	$(MAKE) -f client/cpp/CMakeFiles/vdms-client.dir/build.make client/cpp/CMakeFiles/vdms-client.dir/build
.PHONY : vdms-client/fast

src/BoundingBoxCommand.o: src/BoundingBoxCommand.cc.o

.PHONY : src/BoundingBoxCommand.o

# target to build an object file
src/BoundingBoxCommand.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/BoundingBoxCommand.cc.o
.PHONY : src/BoundingBoxCommand.cc.o

src/BoundingBoxCommand.i: src/BoundingBoxCommand.cc.i

.PHONY : src/BoundingBoxCommand.i

# target to preprocess a source file
src/BoundingBoxCommand.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/BoundingBoxCommand.cc.i
.PHONY : src/BoundingBoxCommand.cc.i

src/BoundingBoxCommand.s: src/BoundingBoxCommand.cc.s

.PHONY : src/BoundingBoxCommand.s

# target to generate assembly for a file
src/BoundingBoxCommand.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/BoundingBoxCommand.cc.s
.PHONY : src/BoundingBoxCommand.cc.s

src/CommunicationManager.o: src/CommunicationManager.cc.o

.PHONY : src/CommunicationManager.o

# target to build an object file
src/CommunicationManager.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/CommunicationManager.cc.o
.PHONY : src/CommunicationManager.cc.o

src/CommunicationManager.i: src/CommunicationManager.cc.i

.PHONY : src/CommunicationManager.i

# target to preprocess a source file
src/CommunicationManager.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/CommunicationManager.cc.i
.PHONY : src/CommunicationManager.cc.i

src/CommunicationManager.s: src/CommunicationManager.cc.s

.PHONY : src/CommunicationManager.s

# target to generate assembly for a file
src/CommunicationManager.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/CommunicationManager.cc.s
.PHONY : src/CommunicationManager.cc.s

src/DescriptorsCommand.o: src/DescriptorsCommand.cc.o

.PHONY : src/DescriptorsCommand.o

# target to build an object file
src/DescriptorsCommand.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/DescriptorsCommand.cc.o
.PHONY : src/DescriptorsCommand.cc.o

src/DescriptorsCommand.i: src/DescriptorsCommand.cc.i

.PHONY : src/DescriptorsCommand.i

# target to preprocess a source file
src/DescriptorsCommand.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/DescriptorsCommand.cc.i
.PHONY : src/DescriptorsCommand.cc.i

src/DescriptorsCommand.s: src/DescriptorsCommand.cc.s

.PHONY : src/DescriptorsCommand.s

# target to generate assembly for a file
src/DescriptorsCommand.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/DescriptorsCommand.cc.s
.PHONY : src/DescriptorsCommand.cc.s

src/DescriptorsManager.o: src/DescriptorsManager.cc.o

.PHONY : src/DescriptorsManager.o

# target to build an object file
src/DescriptorsManager.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/DescriptorsManager.cc.o
.PHONY : src/DescriptorsManager.cc.o

src/DescriptorsManager.i: src/DescriptorsManager.cc.i

.PHONY : src/DescriptorsManager.i

# target to preprocess a source file
src/DescriptorsManager.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/DescriptorsManager.cc.i
.PHONY : src/DescriptorsManager.cc.i

src/DescriptorsManager.s: src/DescriptorsManager.cc.s

.PHONY : src/DescriptorsManager.s

# target to generate assembly for a file
src/DescriptorsManager.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/DescriptorsManager.cc.s
.PHONY : src/DescriptorsManager.cc.s

src/ExceptionsCommand.o: src/ExceptionsCommand.cc.o

.PHONY : src/ExceptionsCommand.o

# target to build an object file
src/ExceptionsCommand.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/ExceptionsCommand.cc.o
.PHONY : src/ExceptionsCommand.cc.o

src/ExceptionsCommand.i: src/ExceptionsCommand.cc.i

.PHONY : src/ExceptionsCommand.i

# target to preprocess a source file
src/ExceptionsCommand.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/ExceptionsCommand.cc.i
.PHONY : src/ExceptionsCommand.cc.i

src/ExceptionsCommand.s: src/ExceptionsCommand.cc.s

.PHONY : src/ExceptionsCommand.s

# target to generate assembly for a file
src/ExceptionsCommand.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/ExceptionsCommand.cc.s
.PHONY : src/ExceptionsCommand.cc.s

src/ImageCommand.o: src/ImageCommand.cc.o

.PHONY : src/ImageCommand.o

# target to build an object file
src/ImageCommand.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/ImageCommand.cc.o
.PHONY : src/ImageCommand.cc.o

src/ImageCommand.i: src/ImageCommand.cc.i

.PHONY : src/ImageCommand.i

# target to preprocess a source file
src/ImageCommand.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/ImageCommand.cc.i
.PHONY : src/ImageCommand.cc.i

src/ImageCommand.s: src/ImageCommand.cc.s

.PHONY : src/ImageCommand.s

# target to generate assembly for a file
src/ImageCommand.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/ImageCommand.cc.s
.PHONY : src/ImageCommand.cc.s

src/PMGDIterators.o: src/PMGDIterators.cc.o

.PHONY : src/PMGDIterators.o

# target to build an object file
src/PMGDIterators.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDIterators.cc.o
.PHONY : src/PMGDIterators.cc.o

src/PMGDIterators.i: src/PMGDIterators.cc.i

.PHONY : src/PMGDIterators.i

# target to preprocess a source file
src/PMGDIterators.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDIterators.cc.i
.PHONY : src/PMGDIterators.cc.i

src/PMGDIterators.s: src/PMGDIterators.cc.s

.PHONY : src/PMGDIterators.s

# target to generate assembly for a file
src/PMGDIterators.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDIterators.cc.s
.PHONY : src/PMGDIterators.cc.s

src/PMGDQuery.o: src/PMGDQuery.cc.o

.PHONY : src/PMGDQuery.o

# target to build an object file
src/PMGDQuery.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDQuery.cc.o
.PHONY : src/PMGDQuery.cc.o

src/PMGDQuery.i: src/PMGDQuery.cc.i

.PHONY : src/PMGDQuery.i

# target to preprocess a source file
src/PMGDQuery.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDQuery.cc.i
.PHONY : src/PMGDQuery.cc.i

src/PMGDQuery.s: src/PMGDQuery.cc.s

.PHONY : src/PMGDQuery.s

# target to generate assembly for a file
src/PMGDQuery.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDQuery.cc.s
.PHONY : src/PMGDQuery.cc.s

src/PMGDQueryHandler.o: src/PMGDQueryHandler.cc.o

.PHONY : src/PMGDQueryHandler.o

# target to build an object file
src/PMGDQueryHandler.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDQueryHandler.cc.o
.PHONY : src/PMGDQueryHandler.cc.o

src/PMGDQueryHandler.i: src/PMGDQueryHandler.cc.i

.PHONY : src/PMGDQueryHandler.i

# target to preprocess a source file
src/PMGDQueryHandler.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDQueryHandler.cc.i
.PHONY : src/PMGDQueryHandler.cc.i

src/PMGDQueryHandler.s: src/PMGDQueryHandler.cc.s

.PHONY : src/PMGDQueryHandler.s

# target to generate assembly for a file
src/PMGDQueryHandler.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/PMGDQueryHandler.cc.s
.PHONY : src/PMGDQueryHandler.cc.s

src/QueryHandler.o: src/QueryHandler.cc.o

.PHONY : src/QueryHandler.o

# target to build an object file
src/QueryHandler.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/QueryHandler.cc.o
.PHONY : src/QueryHandler.cc.o

src/QueryHandler.i: src/QueryHandler.cc.i

.PHONY : src/QueryHandler.i

# target to preprocess a source file
src/QueryHandler.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/QueryHandler.cc.i
.PHONY : src/QueryHandler.cc.i

src/QueryHandler.s: src/QueryHandler.cc.s

.PHONY : src/QueryHandler.s

# target to generate assembly for a file
src/QueryHandler.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/QueryHandler.cc.s
.PHONY : src/QueryHandler.cc.s

src/QueryMessage.o: src/QueryMessage.cc.o

.PHONY : src/QueryMessage.o

# target to build an object file
src/QueryMessage.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/QueryMessage.cc.o
.PHONY : src/QueryMessage.cc.o

src/QueryMessage.i: src/QueryMessage.cc.i

.PHONY : src/QueryMessage.i

# target to preprocess a source file
src/QueryMessage.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/QueryMessage.cc.i
.PHONY : src/QueryMessage.cc.i

src/QueryMessage.s: src/QueryMessage.cc.s

.PHONY : src/QueryMessage.s

# target to generate assembly for a file
src/QueryMessage.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/QueryMessage.cc.s
.PHONY : src/QueryMessage.cc.s

src/RSCommand.o: src/RSCommand.cc.o

.PHONY : src/RSCommand.o

# target to build an object file
src/RSCommand.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/RSCommand.cc.o
.PHONY : src/RSCommand.cc.o

src/RSCommand.i: src/RSCommand.cc.i

.PHONY : src/RSCommand.i

# target to preprocess a source file
src/RSCommand.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/RSCommand.cc.i
.PHONY : src/RSCommand.cc.i

src/RSCommand.s: src/RSCommand.cc.s

.PHONY : src/RSCommand.s

# target to generate assembly for a file
src/RSCommand.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/RSCommand.cc.s
.PHONY : src/RSCommand.cc.s

src/SearchExpression.o: src/SearchExpression.cc.o

.PHONY : src/SearchExpression.o

# target to build an object file
src/SearchExpression.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/SearchExpression.cc.o
.PHONY : src/SearchExpression.cc.o

src/SearchExpression.i: src/SearchExpression.cc.i

.PHONY : src/SearchExpression.i

# target to preprocess a source file
src/SearchExpression.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/SearchExpression.cc.i
.PHONY : src/SearchExpression.cc.i

src/SearchExpression.s: src/SearchExpression.cc.s

.PHONY : src/SearchExpression.s

# target to generate assembly for a file
src/SearchExpression.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/SearchExpression.cc.s
.PHONY : src/SearchExpression.cc.s

src/Server.o: src/Server.cc.o

.PHONY : src/Server.o

# target to build an object file
src/Server.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/Server.cc.o
.PHONY : src/Server.cc.o

src/Server.i: src/Server.cc.i

.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/Server.cc.i
.PHONY : src/Server.cc.i

src/Server.s: src/Server.cc.s

.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/Server.cc.s
.PHONY : src/Server.cc.s

src/VDMSConfig.o: src/VDMSConfig.cc.o

.PHONY : src/VDMSConfig.o

# target to build an object file
src/VDMSConfig.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/VDMSConfig.cc.o
.PHONY : src/VDMSConfig.cc.o

src/VDMSConfig.i: src/VDMSConfig.cc.i

.PHONY : src/VDMSConfig.i

# target to preprocess a source file
src/VDMSConfig.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/VDMSConfig.cc.i
.PHONY : src/VDMSConfig.cc.i

src/VDMSConfig.s: src/VDMSConfig.cc.s

.PHONY : src/VDMSConfig.s

# target to generate assembly for a file
src/VDMSConfig.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/VDMSConfig.cc.s
.PHONY : src/VDMSConfig.cc.s

src/VideoCommand.o: src/VideoCommand.cc.o

.PHONY : src/VideoCommand.o

# target to build an object file
src/VideoCommand.cc.o:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/VideoCommand.cc.o
.PHONY : src/VideoCommand.cc.o

src/VideoCommand.i: src/VideoCommand.cc.i

.PHONY : src/VideoCommand.i

# target to preprocess a source file
src/VideoCommand.cc.i:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/VideoCommand.cc.i
.PHONY : src/VideoCommand.cc.i

src/VideoCommand.s: src/VideoCommand.cc.s

.PHONY : src/VideoCommand.s

# target to generate assembly for a file
src/VideoCommand.cc.s:
	$(MAKE) -f CMakeFiles/dms.dir/build.make CMakeFiles/dms.dir/src/VideoCommand.cc.s
.PHONY : src/VideoCommand.cc.s

src/vdms.o: src/vdms.cc.o

.PHONY : src/vdms.o

# target to build an object file
src/vdms.cc.o:
	$(MAKE) -f CMakeFiles/vdms.dir/build.make CMakeFiles/vdms.dir/src/vdms.cc.o
.PHONY : src/vdms.cc.o

src/vdms.i: src/vdms.cc.i

.PHONY : src/vdms.i

# target to preprocess a source file
src/vdms.cc.i:
	$(MAKE) -f CMakeFiles/vdms.dir/build.make CMakeFiles/vdms.dir/src/vdms.cc.i
.PHONY : src/vdms.cc.i

src/vdms.s: src/vdms.cc.s

.PHONY : src/vdms.s

# target to generate assembly for a file
src/vdms.cc.s:
	$(MAKE) -f CMakeFiles/vdms.dir/build.make CMakeFiles/vdms.dir/src/vdms.cc.s
.PHONY : src/vdms.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... dms"
	@echo "... rebuild_cache"
	@echo "... vdms"
	@echo "... vdms-utils"
	@echo "... vdms_protobuf"
	@echo "... unit_tests"
	@echo "... query_tests"
	@echo "... vcl"
	@echo "... vdms-client"
	@echo "... src/BoundingBoxCommand.o"
	@echo "... src/BoundingBoxCommand.i"
	@echo "... src/BoundingBoxCommand.s"
	@echo "... src/CommunicationManager.o"
	@echo "... src/CommunicationManager.i"
	@echo "... src/CommunicationManager.s"
	@echo "... src/DescriptorsCommand.o"
	@echo "... src/DescriptorsCommand.i"
	@echo "... src/DescriptorsCommand.s"
	@echo "... src/DescriptorsManager.o"
	@echo "... src/DescriptorsManager.i"
	@echo "... src/DescriptorsManager.s"
	@echo "... src/ExceptionsCommand.o"
	@echo "... src/ExceptionsCommand.i"
	@echo "... src/ExceptionsCommand.s"
	@echo "... src/ImageCommand.o"
	@echo "... src/ImageCommand.i"
	@echo "... src/ImageCommand.s"
	@echo "... src/PMGDIterators.o"
	@echo "... src/PMGDIterators.i"
	@echo "... src/PMGDIterators.s"
	@echo "... src/PMGDQuery.o"
	@echo "... src/PMGDQuery.i"
	@echo "... src/PMGDQuery.s"
	@echo "... src/PMGDQueryHandler.o"
	@echo "... src/PMGDQueryHandler.i"
	@echo "... src/PMGDQueryHandler.s"
	@echo "... src/QueryHandler.o"
	@echo "... src/QueryHandler.i"
	@echo "... src/QueryHandler.s"
	@echo "... src/QueryMessage.o"
	@echo "... src/QueryMessage.i"
	@echo "... src/QueryMessage.s"
	@echo "... src/RSCommand.o"
	@echo "... src/RSCommand.i"
	@echo "... src/RSCommand.s"
	@echo "... src/SearchExpression.o"
	@echo "... src/SearchExpression.i"
	@echo "... src/SearchExpression.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/VDMSConfig.o"
	@echo "... src/VDMSConfig.i"
	@echo "... src/VDMSConfig.s"
	@echo "... src/VideoCommand.o"
	@echo "... src/VideoCommand.i"
	@echo "... src/VideoCommand.s"
	@echo "... src/vdms.o"
	@echo "... src/vdms.i"
	@echo "... src/vdms.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

